Mission13/Models/Bowler.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Mission13.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }
        public string BowlerLastName { get; set; }
        public string BowlerFirstName { get; set; }
        public string BowlerMiddleInit { get; set; }
        public string BowlerAddress { get; set; }
        public string BowlerCity { get; set; }
        public string BowlerState { get; set; }
        public string BowlerZip { get; set; }
        public string BowlerPhoneNumber { get; set; }
        public int TeamID { get; set; }
        public Team Team { get; set; }
    }
}

Mission13/Models/BowlingDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace Mission13.Models
{
    public class BowlingDbContext : DbContext
    {
        public BowlingDbContext (DbContextOptions<BowlingDbContext> options) : base (options)
        {
        }

        public DbSet<Bowler> Bowlers { get; set; }

        public DbSet<Team> Teams { get; set; }
    }
}

Mission13/Models/EFBowlersRepository.cs
using System;
using System.Linq;

namespace Mission13.Models
{
    public class EFBowlersRepository : IBowlersRepository
    {
        private BowlingDbContext _context { get; set; }

        public EFBowlersRepository(BowlingDbContext temp)
        {
            _context = temp;
        }

        public IQueryable<Bowler> Bowlers => _context.Bowlers;

        public void SaveBowler(Bowler b)
        {
            _context.Update(b);
            _context.SaveChanges();
        }

        public void CreateBowler(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
        }

        public void DeleteBowler(Bowler b)
        {
            _context.Remove(b);
            _context.SaveChanges();
        }


    }
}

Mission13/Models/EFTeamsRepository.cs
using System;
using System.Linq;

namespace Mission13.Models
{
    public class EFTeamsRepository : ITeamsRepository
    {
        private BowlingDbContext _context { get; set; }

        public EFTeamsRepository(BowlingDbContext temp)
        {
            _context = temp;
        }

        public IQueryable<Team> Teams => _context.Teams;
    }
}

Mission13/Models/IBowlersRepository.cs
using System;
using System.Linq;

namespace Mission13.Models
{
    public interface IBowlersRepository
    {
        IQueryable<Bowler> Bowlers { get; }

        public void SaveBowler(Bowler b);

        public void CreateBowler(Bowler b);

        public void DeleteBowler(Bowler b);
    }
}

Mission13/Models/ITeamsRepository.cs
using System;
using System.Linq;

namespace Mission13.Models
{
    public interface ITeamsRepository
    {
        IQueryable<Team> Teams { get; }
    }
}

Mission13/Models/Team.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Mission13.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }

        public string TeamName { get; set; }

    }
}

Mission13/Components/TypesViewComponent.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission13.Models;

namespace Mission13.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private ITeamsRepository repoT { get; set; }
        public TypesViewComponent (ITeamsRepository tempT)
        {
            repoT = tempT;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewBag.SelectedType = RouteData?.Values["teamName"];

            var types = repoT.Teams
                .Select(x => x.TeamName)
                .Distinct()
                .OrderBy(x => x);
            return View(types);
        }
    }
}

Mission13/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Mission13.Models;

namespace Mission13.Controllers
{
    public class HomeController : Controller
    {
        private IBowlersRepository _repo { get; set; }
        private ITeamsRepository _repoT { get; set; }

        public HomeController(IBowlersRepository temp, ITeamsRepository tempT)
        {
            _repo = temp;
            _repoT = tempT;
        }

        public IActionResult Index(string teamName)
        {
            var bowlers = _repo.Bowlers
                .Include("Team")
                .Where(x => x.Team.TeamName == teamName || teamName == null)
                .ToList();

            return View(bowlers);
        }

        [HttpGet]
        public IActionResult AddBowler()
        {
            ViewBag.Teams = _repoT.Teams.ToList();

            var bowler = _repo.Bowlers.Select(x => x.BowlerID);

            return View("AddEditBowler");
        }

        [HttpPost]
        public IActionResult AddBowler(Bowler b)
        {
            if (ModelState.IsValid)
            {
                _repo.CreateBowler(b);

                return View("Confirmation", b);
            }

            else //if invalid
            {
                ViewBag.Bowlers = _repo.Bowlers.ToList();

                return View(b);
            }

        }

        [HttpGet]
        public IActionResult Edit(int bowlerid)
        {
            ViewBag.Teams = _repoT.Teams.ToList();

            var bowler = _repo.Bowlers.Include("Team")
                .Where(x => x.BowlerID == bowlerid)
                .FirstOrDefault();

            return View("AddEditBowler", bowler);
        }

        [HttpPost]
        public IActionResult Edit(Bowler b)
        {
            _repo.SaveBowler(b);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int bowlerid)
        {
            var bowler = _repo.Bowlers.Single(x => x.BowlerID == bowlerid);

            return View(bowler);
        }

        [HttpPost]
        public IActionResult Delete(Bowler b)
        {
            _repo.DeleteBowler(b);

            return RedirectToAction("Index");
        }

    }
}

Mission13/Views/Home/AddEditBowler.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Bowler 

<div class="text-center">
    <h2>Bowler Info:</h2>

    <!--Form-->
    <form method="post">

        <div asp-validation-summary="All"></div>

        <label asp-for="BowlerFirstName">First Name:</label>
        <input asp-for="BowlerFirstName" /><br />

        <label asp-for="BowlerMiddleInit">Middle Initial:</label>
        <input asp-for="BowlerMiddleInit" /><br />

        <label asp-for="BowlerLastName">Last Name:</label>
        <input asp-for="BowlerLastName" /><br />

        <label asp-for="BowlerAddress">Address:</label>
        <input asp-for="BowlerAddress" /><br />

        <label asp-for="BowlerCity">City:</label>
        <input asp-for="BowlerCity" /><br />

        <label asp-for="BowlerState">State:</label>
        <input asp-for="BowlerState" /><br />

        <label asp-for="BowlerZip">Zip:</label>
        <input asp-for="BowlerZip" /><br />

        <label asp-for="BowlerPhoneNumber">Phone Number:</label>
        <input asp-for="BowlerPhoneNumber" /><br />

        <label asp-for="Team.TeamName">Team Name:</label>
        <select asp-for="Team.TeamName">
            @foreach (Team t in ViewBag.Teams)
            {
                <option value="@t.TeamName">@t.TeamName</option>
            }
        </select>

        <button type="submit">Add Bowler</button>
    </form>
</div>

Mission13/Views/Home/Confirmation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Bowler

<!--Confirmation Message-->
<div class="text-center">
    <h3 class="display-4">@Model.BowlerFirstName was added to Team @Model.Team.TeamName.</h3>
</div>

Mission13/Views/Home/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Bowler

<div class="text-center">
    <h2>Confirm Deletion</h2>
    <h3>Are you sure you want to delete <i>@Model.BowlerID</i>?</h3>

    <form method="post" asp-controller="Home" asp-action="Delete">
        <button type="submit">Delete</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>

        <input type="hidden" asp-for="BowlerID" />
    </form>
</div>

Mission13/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Bowler>

<h1>Bowlers</h1>

<a class="btn btn-primary" asp-controller="Home" asp-action="AddBowler">Create</a>
<br />
<br />

    <table class="table table-bordered table-striped">

        <thead class="font-weight-bold">
            <tr>
                <th>First Name</th>
                <th>Middle Initial</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Phone Number</th>
                <th>Team Name</th>
            </tr>
        </thead>


        @foreach (var b in Model)
        {
            <tr>
                <td>@b.BowlerFirstName</td>
                <td>@b.BowlerMiddleInit</td>
                <td>@b.BowlerLastName</td>
                <td>@b.BowlerAddress</td>
                <td>@b.BowlerCity</td>
                <td>@b.BowlerState</td>
                <td>@b.BowlerZip</td>
                <td>@b.BowlerPhoneNumber</td>
                <td>@b.Team.TeamName</td>

                <td><a asp-controller="Home" asp-action="Edit" asp-route-bowlerid="@b.BowlerID">Edit</a></td>
                <td><a asp-controller="Home" asp-action="Delete" asp-route-bowlerid="@b.BowlerID">Delete</a></td>
            </tr>
        }


    </table>

Mission13/Views/Shared/Components/Types/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<string>

<a asp-controller="Home" asp-action="Index" asp-route-teamName=""
   class="btn @(ViewBag.SelectedType == null ? "btn-primary" : "btn-outline-secondary") col-md">Home</a>

@foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-teamName="@t"
           class="btn @(ViewBag.SelectedType == t ? "btn-primary" : "btn-outline-secondary") col-md">@t</a>
    }

Mission13/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission13</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mission13</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!--Filter-->
    <div class="row m-1">
        <div id="types" class="col-2">
            @await Component.InvokeAsync("Types")
        </div>

        <div class="col-10">
            @RenderBody()
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mission13 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>